<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => '',
    'Meta' => 'Мета',
    'Picture' => 'Изображение',
    'Are you sure you want to delete this item?' => 'Вы уверенны что хотите удалить эту запись?',
    'Blog' => 'Блог',
    'Blog Posts' => 'Записи',
    'Create' => 'Создать',
    'Create Blog Post' => 'Добавить запись',
    'Created At' => 'Создано',
    'Data' => 'Даные',
    'Delete' => 'Удалить',
    'Draft' => 'Черновик',
    'N/A' => 'Не указано',
    'Published' => 'Опубликовано',
    'Reset' => 'Сброк',
    'Search' => 'Поиск',
    'Short Text' => 'Краткий текст',
    'Slug' => 'Псевдоним',
    'Status' => 'Статус',
    'Text' => 'Текст',
    'Title' => 'Заголовок',
    'Update' => 'Редактировать',
    'Update Blog Post:' => 'Редактирование записи: ',
    'Updated At' => 'Редактировано',
];
