<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Duplicate' => 'Скопіювати',
    'ID' => '',
    'Post successfully copied' => 'Запис успішно скопійований',
    'Are you sure you want to delete this item?' => 'Ви дійсно хочете видалити цей запис?',
    'Blog' => 'Блог',
    'Blog Posts' => 'Записи',
    'Create' => 'Створити',
    'Create Blog Post' => 'Додати запис',
    'Created At' => 'Створено',
    'Data' => 'Дані',
    'Delete' => 'Видалити',
    'Draft' => 'Чернетка',
    'Meta' => 'Мета',
    'N/A' => 'Не вказано',
    'Picture' => 'Зображення',
    'Published' => 'Опубліковано',
    'Reset' => 'Скинути',
    'Search' => 'Пошук',
    'Short Text' => 'Короткий текст',
    'Slug' => 'Псевдонім',
    'Status' => 'Статус',
    'Text' => 'Текст',
    'Title' => 'Заголовок',
    'Update' => 'Редагувати',
    'Update Blog Post:' => 'Редагуваня запису',
    'Updated At' => 'Редаговано',
];
